export enum ExamStatus {
  UNRESOLVED = "UNRESOLVED",
  RESOLVED = "RESOLVED",
  WRITING = "WRITING",
  MARKED = "MARKED",
  CREATED = "CREATED",
  GENERATED = "GENERATED",
  FINISHED = "FINISHED",
}
