spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/examination
    username: postgres
    password: apsi_zespol3
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate