spring:
  application:
    name: Examination-module-backend
  profiles:
    active: dev
  mvc:
    dispatch-options-request: true
  sql:
    init:
      mode: never
jwt:
  secrets:
    key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
