spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/osobiste
    username:
    password:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      xc: validate
